#!/bin/bash
function defineColors
{
	RED='\033[0;31m'
	BLUE='\033[0;34m'
	GREEN='\033[0;32m'
	YELLOW='\033[1;33m'
	LIGHTGREEN='\033[1;32m'
	PURPLE='\033[1;35m'
	NC='\033[0m'
}
clear
defineColors
source "$( pwd )/config.sh"
source "$( pwd )/functions.sh"
getAnimSpeed
setAnimSpeed 0.0
echo -e "${RED}"
echo "     $(tput bold)ANDROID AUTOMATION PROJECT     "
echo -e "${YELLOW}"
echo "===================================="
echo "|              APPS                |"
echo "===================================="
echo "|   (W)hatsApp       (I)nstagram   |"
echo "|   (C)amera         (G)allery     |"
echo "|   (Y)ouTube        (P)hone       |"
echo "===================================="
echo "|  Back(<)   Home(0)   Recents(=)  |"
echo "===================================="
printf "${LIGHTGREEN}"
read -p ">>Choice : " choice
echo -e "${NC}"
case $choice in
	'W'|'w')
		WhatsApp
	;;
	'I'|'i')
		Instagram
	;;
	'C'|c)
		Camera
	;;
	'G'|'g')
		Gallery
	;;
	'Y'|'y')
		YouTube
	;;
	'P'|'p')
		Phone
	;;
	'<')
		Back
	;;
	'0'|0)
		Home
	;;
	'=')
		Recent
	;;
esac
echo " "
read -p "Try Again? " choice
if [ "$choice" = "yes" ] || [ "$choice" = "$Yes" ] || [ "$choice" = "YES" ] || [ "$choice" = "YEs" ] || [ "$choice" = "yEs" ] || [ "$choice" = "yES" ] || [ "$choice" = "yeS" ] || [ "$choice" = "YeS" ] || [ "$choice" = "y" ] || [ "$choice" = "Y" ];
then
	bash run
else
	setAnimSpeed $default_window_speed $default_transition_speed $default_animator_duration
	exit 1
fi
